version: "3.8"
services:
  app-server:
    image: happine2s/eye-stock
    container_name: eye-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  redis:
    image: redis:7.2
    container_name: redis-server
    ports:
      - "6379:6379"