version: "3.8"
services:
  app-server:
    image: happine2s/eye-stock
    container_name: eye-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_EXPIRATION=${ACCESS_EXPIRATION}
      - REFRESH_EXPIRATION=${REFRESH_EXPIRATION}
  redis:
    image: redis:7.2
    container_name: redis-server
    ports:
      - "6379:6379"